apiVersion: v1
kind: ConfigMap
metadata:
  name: cookshare-config
  namespace: cookshare-local
  labels:
    app: cookshare
data:
  NODE_ENV: "development"
  NEXTAUTH_URL: "http://localhost:3000"
  UPLOAD_DIR: "/app/public/uploads"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"