global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'web-service'
    static_configs:
      - targets: ['web-service:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'database'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'application'
    static_configs:
      - targets: ['app:3000']
    metrics_path: /actuator/prometheus