apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookshare-app
  namespace: cookshare-local
  labels:
    app: cookshare-app
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookshare-app
  template:
    metadata:
      labels:
        app: cookshare-app
        component: frontend
    spec:
      initContainers:
      - name: migrate
        image: cookshare:latest
        command: ["sh", "-c", "npx prisma generate && npx prisma migrate dev"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cookshare-secret
              key: database-url
        envFrom:
        - configMapRef:
            name: cookshare-config
      containers:
      - name: cookshare-app
        image: cookshare:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cookshare-secret
              key: database-url
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: cookshare-secret
              key: nextauth-secret
        envFrom:
        - configMapRef:
            name: cookshare-config
        volumeMounts:
        - name: upload-storage
          mountPath: /app/public/uploads
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: upload-storage
        persistentVolumeClaim:
          claimName: upload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cookshare-app
  namespace: cookshare-local
  labels:
    app: cookshare-app
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cookshare-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
  namespace: cookshare-local
  labels:
    app: cookshare-app
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage